### ISSUE TITLE
쿠키 토큰이 코드에 그대로 노출되어 있는 문제

### ISSUE THREAD

**Issue by BackGwa** [YongsHub/Bard-ChatBot#1]
`flask/app.py`에 cookie의 토큰 4가지가 코드에 그대로 노출되어 있는 문제가 있습니다.
이를 외부 파일이나 모듈로 생성하여, 불러오시고 해당 파일은 `.gitignore`을 사용하여, 커밋되지 않게 해주시면 좋을 것 같습니다.

**Comment by YongsHub** [comment]
찬영님 안녕하세요! ㅋㅋㅋ
까먹고 그냥 노출시켰는데 감사합니다 :)
